---

- hosts: all
  
  tasks:
    - name: Disallow password authentication
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: Restart SSH
      become: true
      
    - name: Verify that UFW is installed
      apt:
        name: ufw
        state: present
      become: true
      register: ufw_installation
       
    - name: Allow access on SSH port
      ufw:
        port: ssh
        policy: allow
        rule: limit
        proto: tcp
      become: true
      
    - name: Configure UFW to deny access on all ports
      ufw:
        state: enabled
        policy: deny
      become: true
      when: ufw_installation.changed
      
  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
      become: true
      
- hosts: database
  tasks:
    - name: Add APT key for Postgres
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
      become: true
    
    - name: Add APT repo for Postgres
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
        filename: postgres
        state: present
      become: true
        
    - name: Verify installation of PostgreSQL 9.5 and Ansible adapter for Python
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - python-psycopg2
        - postgresql-9.5
      become: true
 
    - name: Verify existence of the f8forum_db
      postgresql_db:
        name: f8forum_db
        state: present
      become_user: postgres
      become: true
    
    - name: Revoke all permissions for the f8forum_db
      postgresql_privs:
        db: f8forum_db
        privs: ALL
        type: database
        role: PUBLIC
        state: absent
      become_user: postgres
      become: true
      
    - name: Add a user for the f8forum_db, granting all rights
      postgresql_user:
        name: f8forum_user
        password: f8forum_user
        db: f8forum_db
        priv: ALL
        role_attr_flags: CREATEDB,NOSUPERUSER
      become_user: postgres
      become: true
        
    - name: Allow postgres access from the Java web application
      lineinfile:
        dest: /etc/postgresql/9.5/main/pg_hba.conf
        line: 'host  all  all   192.168.33.20/24   md5'
      become: true
      notify: Reload postgres
      
    - name: Verify that Postgres listens on all interfaces
      lineinfile:
        dest:  /etc/postgresql/9.5/main/postgresql.conf 
        insertafter: "^#listen_addresses"
        line: "listen_addresses = '*'"
        regexp:  "^listen_addresses"
      become: true   
      notify: Reload postgres
      
    - name: Open port 5432 in UFW
      ufw:
        port: 5432
        policy: allow
      become: true
    
  handlers:
    - name: Reload postgres
      service:
        name: postgresql
        state: reloaded
      become: true
      
      
- hosts: web
  
  tasks:
    - name: Add APT repo for Jessie backports
      apt_repository:
        repo: deb http://ftp.de.debian.org/debian jessie-backports main
        state: present
      become: true
    
    - name: Install OpenJDK 8 JRE
      apt:
        name: openjdk-8-jre
        state: present
        default_release: jessie-backports
        update_cache: yes
      become: true
    
    - name: Create dir /opt/f8forum
      file:
        dest: /opt/f8forum
        state: directory
      become: true
    
    - name: Copy f8forum JAR
      copy:
        src: /vagrant/web/f8forum.jar
        dest: /opt/f8forum/
      become: true  
    
    - name: Copy startup script
      copy:
        src: /vagrant/web/start.sh
        dest: /opt/f8forum/
        mode: 0751
      become: true  
      
    - name: Open port 8080 in UFW
      ufw:
        port: 8080
        policy: allow
      become: true
      
    - name: Copy service script
      copy:
        src: /vagrant/web/f8forum_startscript
        dest: /etc/init.d/f8forum
        mode: 0751
      become: true  
      
    - name: Register application as a service
      command: update-rc.d f8forum defaults
      args:
        creates: /etc/rc5.d/*f8forum
      become: true
      
    - name: Start the F8Forum
      service:
        name: f8forum
        state: started
      become: true
...
